services:
  postgresql:
    image: postgres:16
    container_name: postgresql
    environment:
      POSTGRES_DB: "document-management-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pgdata-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - vkr_network

  minio:
    image: quay.io/minio/minio:RELEASE.2024-05-01T01-11-10Z
    container_name: minio
    command: 'server /data --console-address ":9090"'
    environment:
      - MINIO_ROOT_USER=adminLogin
      - MINIO_ROOT_PASSWORD=ch3Wuetm
    volumes:
      - minio-config-volume:/root/.minio
      - minio-data-volume:/data
    ports:
      - '9000:9000'
      - '9090:9090'
    networks:
      - vkr_network

 # document-management:
 #   image: document-management
 #   volumes:
 #     - document-management-volume:/var/app/data
 #   ports:
 #     - "8080:8080"
 #   networks:
 #     - vkr_network
 #   depends_on:
 #     - postgresql
 #     - minio

volumes:
  minio-config-volume:
    name: docker-minio-config
  minio-data-volume:
    name: docker-minio-data
  pgdata-volume:
    name: docker_pgdata
  document-management-volume:
    name: docker-document-management

networks:
  vkr_network:
    external: true
    attachable: true
    driver: overlay